version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - MODEL_NAME=${MODEL_NAME:-gpt-4-turbo-preview}
      - SUPPORTED_EXTENSIONS=${SUPPORTED_EXTENSIONS:-.py}
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  node_modules:

